### ISSUE TITLE
Missing letters in circle

### ISSUE THREAD

**Issue by libxx1** [raspberrypilearning/secret-messages#43]
URL: /ar-SA/projects/secret-messages/1

هذهِ الدائرة ينقصها حرف ااخاء و الحاء

**Comment by libxx1** [comment]
Hey @majamanojlovic , happy new year. Can you have a look at this issue please. There appears to be missing letters in the circle diagram. Thank you.

**Comment by majamanojlovic** [comment]
@libxx1 Fixed!
